# Generated by Django 4.2.4 on 2023-11-08 13:53

from django.db import migrations


def forwards(apps, schema_editor):
    TipoEvento = apps.get_model("eventos", "TipoEvento")
    Evento = apps.get_model("eventos", "Evento")
    Espaco = apps.get_model("espacos", "Espaco")
    Reserva = apps.get_model("espacos", "Reserva")

    print("")
    for tipo_evento in TipoEvento.objects.filter(categoria="C"):
        print(f"\t Processando {tipo_evento.nome}...")
        espaco = Espaco(
            nome=tipo_evento.nome, sigla=tipo_evento.sigla, local="ILB"
        )
        espaco.save()

        for evento in Evento.objects.filter(tipo_evento=tipo_evento):
            print(f"\t\t Evento {evento.nome}... ", end="")
            if evento.status == "C":  # CANCELADO
                status_reserva = "C"
            else:
                status_reserva = "A"
            reserva = Reserva(
                status=status_reserva,
                espaco=espaco,
                proposito=evento.nome,
                inicio=evento.data_inicio,
                termino=evento.data_termino,
                informacoes=(
                    f"Processo SIGAD: {evento.num_processo}\n"
                    f"{evento.observacao}"
                ),
                solicitante=evento.solicitante,
                contato=evento.descricao[:100],
            )
            reserva.save()
            print("reserva criada... ", end="")
            evento.delete()
            print("evento apagado!")

        tipo_evento.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("espacos", "0001_initial"),
    ]

    operations = [migrations.RunPython(forwards, migrations.RunPython.noop)]
