# Generated by Django 4.2.4 on 2023-12-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("espacos", "0003_reserva_data_pedido_reserva_num_processo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reserva",
            name="status",
            field=models.CharField(
                choices=[("A", "Ativo"), ("C", "Cancelado")],
                default="A",
                max_length=1,
                verbose_name="status",
            ),
        ),
    ]
