# Generated by Django 4.2.7 on 2024-03-12 12:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("espacos", "0004_alter_reserva_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reserva",
            options={
                "ordering": (
                    "data_inicio",
                    "hora_inicio",
                    "espaco",
                    "proposito",
                ),
                "verbose_name": "reserva",
                "verbose_name_plural": "reservas",
            },
        ),
        migrations.RenameField(
            model_name="reserva",
            old_name="inicio",
            new_name="data_inicio",
        ),
        migrations.RenameField(
            model_name="reserva",
            old_name="termino",
            new_name="data_termino",
        ),
        migrations.AddField(
            model_name="espaco",
            name="capacidade",
            field=models.PositiveBigIntegerField(
                default=0,
                help_text="Número de acentos ou lotação máxima do espaço",
                verbose_name="capacidade",
            ),
        ),
        migrations.AddField(
            model_name="espaco",
            name="id_sala",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="ID da sala no sistema de reserva de salas do ILB",
                null=True,
                verbose_name="ID da sala",
            ),
        ),
        migrations.AddField(
            model_name="espaco",
            name="reserva_eventos",
            field=models.BooleanField(
                default=False,
                help_text="Pode ser reservado para eventos cadastrados no SIGI",
                verbose_name="reserva para eventos",
            ),
        ),
        migrations.AddField(
            model_name="recurso",
            name="id_equipamento",
            field=models.PositiveBigIntegerField(
                blank=True,
                help_text="ID do equipamento no sistema de reserva de salas do ILB",
                null=True,
                unique=True,
                verbose_name="ID do equipamento",
            ),
        ),
        migrations.AddField(
            model_name="reserva",
            name="data_ult_atualizacao",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                null=True,
                verbose_name="data da última atualização",
            ),
        ),
        migrations.AddField(
            model_name="reserva",
            name="hora_inicio",
            field=models.TimeField(
                default=django.utils.timezone.now,
                verbose_name="hora início",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reserva",
            name="hora_termino",
            field=models.TimeField(
                default=django.utils.timezone.now,
                verbose_name="hora término",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reserva",
            name="id_reserva",
            field=models.PositiveBigIntegerField(
                blank=True,
                editable=False,
                null=True,
                unique=True,
                verbose_name="ID da reserva",
            ),
        ),
        migrations.AlterField(
            model_name="reserva",
            name="status",
            field=models.CharField(
                choices=[
                    ("A", "Ativo"),
                    ("C", "Cancelado"),
                    ("O", "Conflito de datas"),
                ],
                default="A",
                max_length=1,
                verbose_name="status",
            ),
        ),
    ]
