# Generated by Django 4.2.7 on 2024-03-12 12:39

from datetime import datetime
from django.db import migrations
from django.utils import timezone


def forward(apps, schema_editor):
    Reserva = apps.get_model("espacos", "Reserva")
    for reserva in Reserva.objects.all():
        reserva.hora_inicio = timezone.localtime(reserva.data_inicio).time()
        reserva.hora_termino = timezone.localtime(reserva.data_termino).time()
        reserva.save()


def backward(apps, schema_editor):
    Reserva = apps.get_model("espacos", "Reserva")
    for reserva in Reserva.objects.all():
        reserva.data_inicio = datetime.combine(
            reserva.data_inicio, reserva.hora_inicio
        ).replace(tzinfo=timezone.get_current_timezone())
        reserva.data_termino = datetime.combine(
            reserva.data_termino, reserva.hora_termino
        ).replace(tzinfo=timezone.get_current_timezone())
        reserva.save()


class Migration(migrations.Migration):

    dependencies = [
        ("espacos", "0005_alter_reserva_options_and_more"),
    ]

    operations = [
        migrations.RunPython(forward, backward),
    ]
