# Generated by Django 4.2.7 on 2024-03-12 19:05
from datetime import datetime
from django.db import migrations
from django.db import migrations
from django.conf import settings
from sigi.apps.espacos.jobs.hourly.sincroniza_reservas import Job


def forward(apps, schema_editor):
    start = datetime.now()
    Espaco = apps.get_model("espacos", "Espaco")
    DEPARA_SALAS = [(5, 62), (4, 66), (3, 63)]

    if not Espaco.objects.filter(id__in=[v[0] for v in DEPARA_SALAS]).exists():
        # As salas não existem. Não há nada a fazer.
        return

    for espaco_id, id_sala in DEPARA_SALAS:
        try:
            espaco = Espaco.objects.get(id=espaco_id)
            espaco.id_sala = id_sala
            espaco.save()
        except Espaco.DoesNotExist:
            pass

    if (
        settings.RESERVA_SALA_BASE_URL is None
        or settings.RESERVA_SALA_API_USER is None
        or settings.RESERVA_SALA_API_PASSWORD is None
    ):
        # Acesso ao sistema não configurado. Não fazer nada
        return

    job = Job()
    job.carrega_salas()
    job.carrega_recursos()
    job.carrega_reservas(ontem="2023-12-31")
    job.report(start, datetime.now())


class Migration(migrations.Migration):

    dependencies = [
        (
            "espacos",
            "0007_alter_reserva_data_inicio_alter_reserva_data_termino",
        ),
    ]

    operations = [migrations.RunPython(forward, migrations.RunPython.noop)]
