version: "3.3"
   
services:
  db:
    image: postgres:12.9
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=sigi
      - POSTGRES_PASSWORD=123456
  code:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=sigi
      - POSTGRES_PASSWORD=132456
    depends_on:
      - db

