# Generated by Django 4.0.4 on 2022-05-16 18:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "servicos",
            "0010_delete_casaatendida_alter_tiposervico_options_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servico",
            name="contato_administrativo",
        ),
        migrations.RemoveField(
            model_name="servico",
            name="contato_tecnico",
        ),
        migrations.RemoveField(
            model_name="servico",
            name="nome_servidor",
        ),
        migrations.RemoveField(
            model_name="servico",
            name="porta_servico",
        ),
        migrations.RemoveField(
            model_name="servico",
            name="senha_inicial",
        ),
        migrations.AlterField(
            model_name="tiposervico",
            name="template_email_altera",
            field=models.TextField(
                blank=True,
                help_text="Use a marcação {url} para incluir a URL do serviço,<br/>",
                verbose_name="template de email de alteração",
            ),
        ),
        migrations.AlterField(
            model_name="tiposervico",
            name="template_email_ativa",
            field=models.TextField(
                blank=True,
                help_text="Use a marcação {url} para incluir a URL do serviço,<br/>",
                verbose_name="template de email de ativação",
            ),
        ),
        migrations.AlterField(
            model_name="tiposervico",
            name="template_email_desativa",
            field=models.TextField(
                blank=True,
                help_text="Use a marcação {url} para incluir a URL do serviço,<br/><br/>{motivo} para incluir o motivo da desativação do serviço",
                verbose_name="template de email de desativação",
            ),
        ),
    ]
