# Generated by Django 4.0.4 on 2022-05-17 13:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0012_servico_data_verificacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logservico',
            name='data',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Data da ação'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='data_ativacao',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Data de ativação'),
        ),
    ]
