# Generated by Django 4.1.2 on 2022-10-20 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servicos", "0013_alter_logservico_data_alter_servico_data_ativacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="servico",
            name="instancia",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="nome da instância"
            ),
        ),
        migrations.AddField(
            model_name="servico",
            name="versao",
            field=models.CharField(blank=True, max_length=20, verbose_name="versão"),
        ),
        migrations.AddField(
            model_name="tiposervico",
            name="arquivo_rancher",
            field=models.CharField(
                blank=True,
                max_length=100,
                verbose_name="nome do arquivo gerado no rancher",
            ),
        ),
        migrations.AddField(
            model_name="tiposervico",
            name="prefixo_padrao",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="tiposervico",
            name="spec_rancher",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="spec do serviço no Rancher"
            ),
        ),
        migrations.AddField(
            model_name="tiposervico",
            name="tipo_rancher",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="tipo de objeto no Rancher"
            ),
        ),
    ]
