# Generated by Django 4.1.1 on 2022-10-03 21:00

from django.db import migrations
from sigi.apps.servicos import generate_instance_name


def instance_names_fw(apps, schema_editor):
    Servico = apps.get_model("servicos", "Servico")
    for s in Servico.objects.filter(data_desativacao=None):
        s.instancia = generate_instance_name(s.casa_legislativa)
        s.save()


def instance_names_rw(apps, schema_editor):
    Servico = apps.get_model("servicos", "Servico")
    Servico.objects.all().update(instancia="")


class Migration(migrations.Migration):

    dependencies = [
        ("servicos", "0014_servico_instancia_servico_versao_and_more"),
    ]

    operations = [
        migrations.RunPython(instance_names_fw, instance_names_rw),
    ]
