# Generated by Django 4.1.2 on 2022-10-24 13:28

from django.db import migrations


def instance_names_fw(apps, schema_editor):
    Servico = apps.get_model("servicos", "Servico")
    seq = 0
    for s in Servico.objects.filter(instancia="").exclude(
        data_desativacao=None
    ):
        s.instancia = f"instancia-desativada-{seq}"
        s.save()
        seq += 1
    print(f"{seq} instâncias fakeadas")


def instance_names_rw(apps, schema_editor):
    Servico = apps.get_model("servicos", "Servico")
    Servico.objects.filter(instancia__startswith="instancia-desativada").update(
        instancia=""
    )


class Migration(migrations.Migration):

    dependencies = [
        ("servicos", "0015_nomeia_instancias"),
    ]

    operations = [
        migrations.RunPython(instance_names_fw, instance_names_rw),
    ]
