# Generated by Django 4.1.2 on 2022-10-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "servicos",
            "0016_prepare_unique_tipo_servico_instancia_data_desativacao",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="servico",
            options={
                "verbose_name": "serviço SEIT",
                "verbose_name_plural": "serviços SEIT",
            },
        ),
        migrations.AddConstraint(
            model_name="servico",
            constraint=models.UniqueConstraint(
                fields=("tipo_servico", "instancia", "data_desativacao"),
                name="unique_instance",
            ),
        ),
    ]
