# Generated by Django 4.1.2 on 2022-10-25 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servicos", "0017_alter_servico_options_servico_unique_instance"),
    ]

    operations = [
        migrations.AddField(
            model_name="servico",
            name="flag_confirmado",
            field=models.BooleanField(
                default=False, verbose_name="indica se o registro foi confirmado"
            ),
        ),
    ]
