# Generated by Django 4.1.4 on 2023-01-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("servicos", "0020_servico_apps"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="servico",
            name="unique_instance",
        ),
        migrations.AddConstraint(
            model_name="servico",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("data_desativacao", None),
                    models.Q(("instancia", ""), _negated=True),
                ),
                fields=("tipo_servico", "instancia", "url"),
                name="unique_instance",
            ),
        ),
    ]
