# Generated by Django 6.0.4 on 2026-08-07 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("servicos", "0022_atualiza_mail_leg"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tiposervico",
            name="arquivo_rancher",
        ),
        migrations.RemoveField(
            model_name="tiposervico",
            name="spec_rancher",
        ),
    ]
