# Generated by Django 4.1 on 2022-08-10 18:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ocorrencias", "0010_alter_ocorrencia_options_ocorrencia_interno"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoria",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("C", "Solicitação de convênio (ACT)"),
                    ("E", "Solicitação de evento (oficina)"),
                    ("O", "Outras"),
                ],
                default="O",
                max_length=1,
                verbose_name="Tipo de solicitação",
            ),
        ),
    ]
