# Generated by Django 4.1 on 2022-09-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocorrencias", "0011_alter_categoria_tipo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comentario",
            name="descricao",
            field=models.TextField(blank=True, null=True, verbose_name="Comentário"),
        ),
    ]
