# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-11 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servidores', '0002_auto_20160623_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servidor',
            name='foto',
            field=models.ImageField(blank=True, height_field=b'foto_altura', null=True, upload_to=b'fotos/servidores', width_field=b'foto_largura'),
        ),
    ]
