# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-12 15:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servidores', '0003_auto_20160811_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servidor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
