# Generated by Django 4.0.4 on 2022-05-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servidores', '0008_alter_servico_id_alter_servidor_foto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servidor',
            name='cargo',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
