# Generated by Django 4.0.5 on 2022-06-30 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servidores', '0009_servidor_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='servidor',
            name='sigi',
            field=models.BooleanField(default=False, editable=False, verbose_name='Servidor SIGI'),
        ),
    ]
