# Generated by Django 4.1 on 2022-08-17 15:18

from django.db import migrations


def forwards_migration(apps, schema_editor):
    Servidor = apps.get_model("servidores", "Servidor")
    Servico = apps.get_model("servidores", "Servico")

    ilb = Servico.objects.filter(subordinado=None).first()
    if ilb is None:
        return

    sigi = {
        "apelido": "SIGI",
        "cargo": "Usuário do sistema",
        "nome_completo": "SIGI - Sistema de Informações do Interlegis",
        "servico": ilb,
    }
    Servidor.objects.update_or_create(defaults=sigi, sigi=True)


def reverse_migration(apps, schema_editor):
    Servidor = apps.get_model("servidores", "Servidor")
    Servidor.objects.filter(sigi=True).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("servidores", "0010_servidor_sigi"),
    ]

    operations = [
        migrations.RunPython(forwards_migration, reverse_migration),
    ]
