# Generated by Django 4.0.1 on 2022-01-06 23:50

from django.db import migrations, models
import django.db.models.deletion
import sigi.apps.utils


class Migration(migrations.Migration):

    dependencies = [
        ("contatos", "0004_auto_20210611_0946"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mesorregiao",
            options={
                "ordering": ("uf", "nome"),
                "verbose_name": ("mesorregião",),
                "verbose_name_plural": "mesorregiões",
            },
        ),
        migrations.AlterModelOptions(
            name="microrregiao",
            options={
                "ordering": ("nome",),
                "verbose_name": "microrregião",
                "verbose_name_plural": "microrregiões",
            },
        ),
        migrations.AlterField(
            model_name="contato",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="e-mail"
            ),
        ),
        migrations.AlterField(
            model_name="contato",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="endereco",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="endereco",
            name="logradouro",
            field=models.CharField(max_length=100, verbose_name="logradouro"),
        ),
        migrations.AlterField(
            model_name="endereco",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("aeroporto", "Aeroporto"),
                    ("alameda", "Alameda"),
                    ("area", "Área"),
                    ("avenida", "Avenida"),
                    ("campo", "Campo"),
                    ("chacara", "Chácara"),
                    ("colonia", "Colônia"),
                    ("condominio", "Condomínio"),
                    ("conjunto", "Conjunto"),
                    ("distrito", "Distrito"),
                    ("esplanada", "Esplanada"),
                    ("estacao", "Estação"),
                    ("estrada", "Estrada"),
                    ("favela", "Favela"),
                    ("fazenda", "Fazenda"),
                    ("feira", "Feira"),
                    ("jardim", "Jardim"),
                    ("ladeira", "Ladeira"),
                    ("lago", "Lago"),
                    ("lagoa", "Lagoa"),
                    ("largo", "Largo"),
                    ("loteamento", "Loteamento"),
                    ("morro", "Morro"),
                    ("nucleo", "Núcleo"),
                    ("parque", "Parque"),
                    ("passarela", "Passarela"),
                    ("patio", "Pátio"),
                    ("praca", "Praça"),
                    ("quadra", "Quadra"),
                    ("recanto", "Recanto"),
                    ("residencial", "Residencial"),
                    ("rodovia", "Rodovia"),
                    ("rua", "Rua"),
                    ("setor", "Setor"),
                    ("sitio", "Sítio"),
                    ("travessa", "Travessa"),
                    ("trecho", "Trecho"),
                    ("trevo", "Trevo"),
                    ("vale", "Vale"),
                    ("vereda", "Vereda"),
                    ("via", "Via"),
                    ("viaduto", "Viaduto"),
                    ("viela", "Viela"),
                    ("vila", "Vila"),
                    ("outro", "Outro"),
                ],
                max_length=15,
                verbose_name="tipo",
            ),
        ),
        migrations.AlterField(
            model_name="mesorregiao",
            name="codigo_ibge",
            field=models.PositiveIntegerField(
                help_text="Código da mesorregião segundo o IBGE",
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="código IBGE",
            ),
        ),
        migrations.AlterField(
            model_name="mesorregiao",
            name="nome",
            field=models.CharField(
                max_length=100, verbose_name="nome mesorregião"
            ),
        ),
        migrations.AlterField(
            model_name="mesorregiao",
            name="search_text",
            field=sigi.apps.utils.SearchField(
                editable=False, field_names=["nome"]
            ),
        ),
        migrations.AlterField(
            model_name="microrregiao",
            name="codigo_ibge",
            field=models.PositiveIntegerField(
                help_text="Código da microrregião segundo o IBGE",
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="código IBGE",
            ),
        ),
        migrations.AlterField(
            model_name="microrregiao",
            name="mesorregiao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contatos.mesorregiao",
                verbose_name="mesorregião",
            ),
        ),
        migrations.AlterField(
            model_name="microrregiao",
            name="nome",
            field=models.CharField(
                max_length=100, verbose_name="nome microrregião"
            ),
        ),
        migrations.AlterField(
            model_name="microrregiao",
            name="search_text",
            field=sigi.apps.utils.SearchField(
                editable=False, field_names=["nome"]
            ),
        ),
        migrations.AlterField(
            model_name="municipio",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                help_text="Exemplo: <em>-20,464</em>.",
                max_digits=10,
                null=True,
                verbose_name="latitude",
            ),
        ),
        migrations.AlterField(
            model_name="municipio",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                help_text="Exemplo: <em>-45,426</em>.",
                max_digits=11,
                null=True,
                verbose_name="longitude",
            ),
        ),
        migrations.AlterField(
            model_name="municipio",
            name="microrregiao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="contatos.microrregiao",
                verbose_name="microrregião",
            ),
        ),
        migrations.AlterField(
            model_name="telefone",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="telefone",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("F", "Fixo"),
                    ("M", "Móvel"),
                    ("X", "Fax"),
                    ("I", "Indefinido"),
                ],
                default="I",
                max_length=1,
                verbose_name="tipo",
            ),
        ),
        migrations.AlterField(
            model_name="telefone",
            name="ult_alteracao",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="última alteração"
            ),
        ),
        migrations.AlterField(
            model_name="unidadefederativa",
            name="nome",
            field=models.CharField(max_length=25, verbose_name="nome UF"),
        ),
        migrations.AlterField(
            model_name="unidadefederativa",
            name="regiao",
            field=models.CharField(
                choices=[
                    ("CO", "Centro-Oeste"),
                    ("NE", "Nordeste"),
                    ("NO", "Norte"),
                    ("SD", "Sudeste"),
                    ("SL", "Sul"),
                ],
                max_length=2,
                verbose_name="região",
            ),
        ),
        migrations.AlterField(
            model_name="unidadefederativa",
            name="search_text",
            field=sigi.apps.utils.SearchField(
                editable=False, field_names=["nome"]
            ),
        ),
        migrations.AlterField(
            model_name="unidadefederativa",
            name="sigla",
            field=models.CharField(
                help_text="Exemplo: <em>MG</em>.",
                max_length=2,
                unique=True,
                verbose_name="sigla",
            ),
        ),
    ]
