# Generated by Django 4.0.3 on 2022-04-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eventos", "0017_alter_anexo_arquivo_alter_anexo_descricao_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="data_pedido",
            field=models.DateField(
                blank=True,
                help_text="Data em que o pedido do Gabinete chegou à COPERI",
                null=True,
                verbose_name="Data do pedido",
            ),
        ),
        migrations.AddField(
            model_name="evento",
            name="num_processo",
            field=models.CharField(
                blank=True,
                help_text="Formato:<em>XXXXX.XXXXXX/XXXX-XX</em>",
                max_length=20,
                verbose_name="número do processo SIGAD",
            ),
        ),
        migrations.AddField(
            model_name="evento",
            name="observacao",
            field=models.TextField(
                blank=True, verbose_name="Observações e anotações"
            ),
        ),
        migrations.AlterField(
            model_name="evento",
            name="status",
            field=models.CharField(
                choices=[
                    ("E", "Em planejamento"),
                    ("G", "Aguardando abertura SIGAD"),
                    ("P", "Previsão"),
                    ("A", "A confirmar"),
                    ("O", "Confirmado"),
                    ("R", "Realizado"),
                    ("C", "Cancelado"),
                ],
                max_length=1,
                verbose_name="Status",
            ),
        ),
    ]
