# Generated by Django 4.0.4 on 2022-05-05 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("eventos", "0019_alter_evento_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="anexo",
            name="convite",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="eventos.convite",
            ),
        ),
    ]
