# Generated by Django 4.0.4 on 2022-05-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0020_anexo_convite'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='assina_oficio',
            field=models.BooleanField(default=False, verbose_name='Assina ofício de comparecimento'),
        ),
    ]
