# Generated by Django 4.0.4 on 2022-05-17 13:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0021_equipe_assina_oficio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anexo',
            name='data_pub',
            field=models.DateTimeField(default=django.utils.timezone.localtime, verbose_name='data da publicação do anexo'),
        ),
    ]
