# Generated by Django 4.1.2 on 2022-11-11 18:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("eventos", "0028_evento_solicitacao"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="convite",
            options={
                "ordering": ("evento", "casa"),
                "verbose_name": "Casa convidada",
                "verbose_name_plural": "Casas convidadas",
            },
        ),
        migrations.RemoveField(
            model_name="convite",
            name="aceite",
        ),
        migrations.RemoveField(
            model_name="convite",
            name="data_convite",
        ),
        migrations.RemoveField(
            model_name="convite",
            name="participou",
        ),
        migrations.RemoveField(
            model_name="convite",
            name="servidor",
        ),
    ]
