# Generated by Django 4.1.7 on 2023-03-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eventos", "0029_alter_convite_options_remove_convite_aceite_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evento",
            name="descricao",
            field=models.TextField(
                default="solicitar Acordo de Cooperação Técnica entre a Câmara Municipal e esta Escola de Governo do Senado Federal. Na ocasião foram apresentados os produtos e serviços oferecidos gratuitamente pelo Programa Interlegis",
                verbose_name="Descrição do evento",
            ),
        ),
        migrations.AlterField(
            model_name="tipoevento",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("C", "Curso"),
                    ("E", "Encontro"),
                    ("O", "Oficina"),
                    ("S", "Seminário"),
                    ("V", "Visita"),
                ],
                max_length=1,
                verbose_name="Categoria",
            ),
        ),
    ]
