# Generated by Django 4.1.7 on 2023-04-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eventos", "0030_alter_evento_descricao_alter_tipoevento_categoria"),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="moodle_courseid",
            field=models.PositiveBigIntegerField(
                blank=True,
                help_text="ID do curso no Saberes. Este campo é preenchido automaticamente quando o curso é criado no Saberes.",
                null=True,
                verbose_name="ID do curso",
            ),
        ),
    ]
