# Generated by Django 4.1.7 on 2023-04-14 15:02

from django.db import migrations


def set_courseid(apps, schema_editor):
    Evento = apps.get_model("eventos", "Evento")
    for evento in Evento.objects.exclude(link_inscricao=""):
        if "=" in evento.link_inscricao:
            evento.moodle_courseid = int(evento.link_inscricao.split("=")[1])
            evento.save()


def reset_courseid(apps, schema_editor):
    from django.conf import settings

    Evento = apps.get_model("eventos", "Evento")
    for evento in Evento.objects.exclude(moodle_courseid=None):
        evento.link_inscricao = (
            settings.MOODLE_BASE_URL
            + f"/course/view.php?id={evento.moodle_courseid}"
        )
        evento.save()


class Migration(migrations.Migration):
    dependencies = [
        ("eventos", "0031_evento_moodle_courseid"),
    ]

    operations = [
        migrations.RunPython(set_courseid, reset_courseid),
    ]
