# Generated by Django 4.1.7 on 2023-04-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eventos", "0033_remove_evento_link_inscricao"),
    ]

    operations = [
        migrations.AddField(
            model_name="funcao",
            name="moodle_roleid",
            field=models.PositiveBigIntegerField(
                blank=True,
                help_text="Código do papel do membro da equipe no Saberes",
                null=True,
                verbose_name="Papel Saberes",
            ),
        ),
        migrations.AddField(
            model_name="tipoevento",
            name="moodle_categoryid",
            field=models.PositiveBigIntegerField(
                blank=True,
                help_text="Código da categoria no Saberes onde o curso deve ser criado.",
                null=True,
                verbose_name="Categoria do curso",
            ),
        ),
        migrations.AddField(
            model_name="tipoevento",
            name="moodle_template_courseid",
            field=models.PositiveBigIntegerField(
                blank=True,
                help_text="Código do curso que serve de protótipo no Saberes para criação de novos eventos desse tipo.",
                null=True,
                verbose_name="Curso protótipo",
            ),
        ),
    ]
