# Generated by Django 4.1.7 on 2023-04-18 19:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "eventos",
            "0034_funcao_moodle_roleid_tipoevento_moodle_categoryid_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="evento",
            options={
                "ordering": ("-data_inicio",),
                "permissions": [
                    (
                        "createcourse_evento",
                        "Can create courses in Saberes platform",
                    )
                ],
                "verbose_name": "Evento",
                "verbose_name_plural": "Eventos",
            },
        ),
    ]
