# Generated by Django 4.1.7 on 2023-05-09 13:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eventos", "0035_alter_evento_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="tipoevento",
            name="prefixo_turma",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Prefixo para turmas"
            ),
        ),
        migrations.AlterField(
            model_name="evento",
            name="turma",
            field=models.CharField(
                blank=True,
                max_length=100,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{2}/\\d{4}$",
                        "Formato inválido. Utilize nn/aaaa, onde 'nn' são dígitos numéricos e 'aaaa' o ano com quatro dígitos.",
                    )
                ],
                verbose_name="turma",
            ),
        ),
    ]
