# Generated by Django 4.2.4 on 2023-09-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "eventos",
            "0039_remove_evento_municipio_evento_data_recebido_coperi_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemsolicitado",
            name="data_analise",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                null=True,
                verbose_name="data de autorização/rejeição",
            ),
        ),
        migrations.AlterField(
            model_name="solicitacao",
            name="contato",
            field=models.CharField(
                blank=True,
                max_length=100,
                verbose_name="pessoa de contato na Casa",
            ),
        ),
    ]
