# Generated by Django 4.2.4 on 2023-09-13 22:20

from django.db import migrations


def forwards(apps, schema_editor):
    Solicitacao = apps.get_model("eventos", "Solicitacao")

    for s in Solicitacao.objects.all():
        statuses = list(
            s.itemsolicitado_set.values_list("status", flat=True).distinct(
                "status"
            )
        )
        if statuses == ["S"]:
            s.status = "S"
        elif statuses == ["A"]:
            s.status = "C"
        elif statuses == ["R"]:
            s.status = "R"
        elif "S" in statuses and ("A" in statuses or "R" in statuses):
            s.status = "A"
        s.save()


class Migration(migrations.Migration):
    dependencies = [
        (
            "eventos",
            "0041_solicitacao_data_analise_solicitacao_justificativa_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(
            forwards,
        )
    ]
