# Generated by Django 4.2.4 on 2023-09-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eventos", "0046_tipoevento_gerar_turma_alter_evento_turma"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evento",
            name="contato_inscricao",
            field=models.CharField(
                blank=True,
                default="Central de Atendimento - Oficinas.",
                help_text="pessoa ou setor responsável por dar suporte aos alunos no processo de inscrição",
                max_length=100,
                verbose_name="contato para inscrição",
            ),
        ),
        migrations.AlterField(
            model_name="evento",
            name="observacao_inscricao",
            field=models.TextField(
                blank=True,
                default="Passo a passo para a inscrição:<BR>1. Acesse a plataforma Saberes para ir direto ao curso.<BR>2. Para efetivar a matrícula, insira a CHAVE DE INSCRIÇÃO indicada acima.<BR>3. Dentro da plataforma Saberes, preencha o PERFIL DO ESTUDANTE e junte-se ao grupo do Whatsapp para receber informações.<BR>4. No dia da Oficina, leve seu notebook com mouse, se possível.<BR>ATENÇÃO: as inscrições ficarão abertas até o dia anterior ao início da Oficina (14h), ou até atingir o número máximo de participantes.",
                help_text="Mais detalhes para ajudar o aluno a se inscrever no curso",
                verbose_name="Observações para inscrição",
            ),
        ),
        migrations.AlterField(
            model_name="evento",
            name="telefone_inscricao",
            field=models.CharField(
                blank=True,
                default="(61)3303-2026 ; (61)99862-7973 (zap)",
                help_text="telefone da pessoa ou setor responsável por dar suporte aos alunos no processo de inscrição",
                max_length=60,
                verbose_name="telefone do contato",
            ),
        ),
    ]
