# Generated by Django 4.2.4 on 2023-10-03 13:51

from django.db import migrations

# Os status dos eventos serão simplificados para o seguinte:
#
# STATUS_PREVISTO     substituirá o atual STATUS_PREVISAO
# STATUS_AUTORIZADO   substituirá o atual STATUS_CONFIRMADO
# STATUS_SOBRESTADO   substituirá o atual STATUS_ARQUIVADO
# STATUS_CANCELADO    mantém igual
# STATUS_REALIZADO    mantém igual
#
# Os eventos que estejam em um status que será eliminado deverá migrar
# para outro status seguindo as regras abaixo:
#
# Status atual           => muda para
# ----------------------    ---------------
# STATUS_PLANEJAMENTO    => STATUS_PREVISAO
# STATUS_AGUARDANDOSIGAD => STATUS_PREVISAO
# STATUS_ACONFIRMAR      => STATUS_PREVISAO


def forwards(apps, schema_editor):
    Evento = apps.get_model("eventos", "Evento")

    STATUS_PLANEJAMENTO = "E"
    STATUS_AGUARDANDOSIGAD = "G"
    STATUS_PREVISAO = "P"
    STATUS_ACONFIRMAR = "A"

    Evento.objects.filter(
        status__in=[
            STATUS_PLANEJAMENTO,
            STATUS_AGUARDANDOSIGAD,
            STATUS_ACONFIRMAR,
        ]
    ).update(status=STATUS_PREVISAO)


class Migration(migrations.Migration):
    dependencies = [
        ("eventos", "0050_alter_evento_total_participantes"),
    ]

    operations = [migrations.RunPython(forwards, migrations.RunPython.noop)]
