# Generated by Django 4.2.4 on 2023-10-25 13:51

from django.db import migrations


def forwards(apps, schema_editor):
    Evento = apps.get_model("eventos", "Evento")
    Orgao = apps.get_model("casas", "orgao")

    # Define casa_anfitria = senado para todas as visitas
    # Gertik #165751 (2)

    senado = Orgao.objects.get(tipo__sigla="SF")

    Evento.objects.filter(tipo_evento__categoria="V").update(
        casa_anfitria=senado
    )

    # Deletar todos os convites (casas convidadas) das oficinas que têm vínculo
    # com o saberes moodle_courseid not NULL
    # Gertik #165984: https://gertiq.senado.leg.br/redmine/issues/165984#3em-seguida-DELETAR-as-Casas-convidadas-DOS-registros-de-OFICINAS

    for oficina in Evento.objects.filter(tipo_evento__categoria="O").exclude(
        moodle_courseid=None
    ):
        oficina.convite_set.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        (
            "eventos",
            "0052_alter_evento_status_alter_itemsolicitado_status_and_more",
        ),
    ]

    operations = [migrations.RunPython(forwards, migrations.RunPython.noop)]
