# Generated by Django 4.2.4 on 2023-11-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eventos", "0053_visita_anfitria_senado_oficina_remove_convite"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipe",
            name="emissao_passagens",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="data de emissão das passagens",
            ),
        ),
        migrations.AddField(
            model_name="equipe",
            name="qtde_diarias",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="quantidade de diárias"
            ),
        ),
        migrations.AddField(
            model_name="equipe",
            name="total_passagens",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=14,
                null=True,
                verbose_name="valor total das passagens",
            ),
        ),
        migrations.AddField(
            model_name="equipe",
            name="valor_diaria",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=14,
                null=True,
                verbose_name="valor da diária (R$)",
            ),
        ),
    ]
