# Generated by Django 4.2.4 on 2023-12-01 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("espacos", "0003_reserva_data_pedido_reserva_num_processo_and_more"),
        (
            "eventos",
            "0054_equipe_emissao_passagens_equipe_qtde_diarias_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="reserva",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="espacos.reserva",
            ),
        ),
    ]
