# Generated by Django 4.2.7 on 2024-03-13 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0056_evento_origem_sincronizacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='qtde_diarias',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='quantidade de diárias'),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='valor_diaria',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='valor unitário da diária (R$)'),
        ),
    ]
