# Generated by Django 4.2.7 on 2024-03-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "eventos",
            "0057_alter_equipe_qtde_diarias_alter_equipe_valor_diaria",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="hora_inicio",
            field=models.TimeField(
                blank=True, null=True, verbose_name="hora início"
            ),
        ),
        migrations.AddField(
            model_name="evento",
            name="hora_termino",
            field=models.TimeField(
                blank=True, null=True, verbose_name="hora término"
            ),
        ),
    ]
