# Generated by Django 4.2.7 on 2024-03-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0060_drop_viw_eventos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evento",
            name="data_inicio",
            field=models.DateField(
                blank=True, null=True, verbose_name="data início"
            ),
        ),
        migrations.AlterField(
            model_name="evento",
            name="data_termino",
            field=models.DateField(
                blank=True, null=True, verbose_name="data término"
            ),
        ),
    ]
