# Generated by Django 4.2.7 on 2024-03-12 14:50

from django.db import migrations

SQL_STMT = """
create view viw_eventos as
select e.id, e.nome, e.descricao, e.solicitante, (e.data_inicio + e.hora_inicio) as data_inicio,
       (e.data_termino + e.hora_termino) as data_termino, e.local, e.publico_alvo, 
      (case
        when e.status = 'P' then 'Previsto'
        when e.status = 'O' then 'Autorizado'
        when e.status = 'R' then 'Realizado'
        when e.status = 'C' then 'Cancelado'
        when e.status = 'Q' then 'Sobrestado'
        else e.status -- Fallback retorna a sigla do status
       end) as status,
       e.data_cancelamento, e.motivo_cancelamento,
       e.casa_anfitria_id, o.nome as casa_anfitria,
       o.municipio_id, m.nome as municipio, uf.sigla as uf_sigla,
       uf.nome as uf_nome, t.nome as tipo_evento,
       (case
         when t.categoria='C' then 'Curso'
         when t.categoria='E' then 'Encontro'
         when t.categoria='O' then 'Oficina'
         when t.categoria='S' then 'Seminário'
         when t.categoria='V' then 'Visita'
       end) as categoria,
       e.virtual, e.total_participantes,
       e.data_pedido, e.num_processo, e.observacao, e.turma
from eventos_evento e
  inner join casas_orgao o on o.id = e.casa_anfitria_id
  inner join contatos_municipio m on m.codigo_ibge = o.municipio_id
  inner join contatos_unidadefederativa uf on uf.codigo_ibge = m.uf_id
  inner join eventos_tipoevento t on t.id = e.tipo_evento_id;
grant select on viw_eventos to sigi_qs;
"""
SQL_REVERSE_STMT = "DROP VIEW viw_eventos;"


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0061_alter_evento_data_inicio_alter_evento_data_termino"),
    ]

    operations = [
        migrations.RunSQL(sql=SQL_STMT, reverse_sql=SQL_REVERSE_STMT)
    ]
