# Generated by Django 5.0.4 on 2024-05-28 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contatos", "0007_alter_mesorregiao_options"),
        ("eventos", "0062_create_viw_eventos"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParticipantesEvento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inscritos",
                    models.PositiveIntegerField(
                        default=0, verbose_name="total de inscritos"
                    ),
                ),
                (
                    "aprovados",
                    models.PositiveIntegerField(
                        default=0, verbose_name="total de aprovados"
                    ),
                ),
                (
                    "evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eventos.evento",
                        verbose_name="evento",
                    ),
                ),
                (
                    "uf",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contatos.unidadefederativa",
                        verbose_name="uf",
                    ),
                ),
            ],
            options={
                "verbose_name": "Participante por UF",
                "verbose_name_plural": "Participantes por UF",
            },
        ),
        migrations.AddConstraint(
            model_name="participantesevento",
            constraint=models.UniqueConstraint(
                models.F("evento"), models.F("uf"), name="unique_evento_uf"
            ),
        ),
    ]
