# Generated by Django 5.2.1 on 2025-08-29 14:08

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("casas", "0027_alter_orgao_email"),
        ("eventos", "0063_participantesevento_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modelodeclaracao",
            name="texto",
            field=tinymce.models.HTMLField(
                help_text="Use as seguintes marcações:<ul><li>{{ casa.nome }} para o nome da Casa Legislativa / órgão</li><li>{{ casa.municipio.uf.sigla }} para a sigla da UF da Casa legislativa</li><li>{{ participante.cpf }} para o CPF do visitante</li><li>{{ participante.nome }} para o nome do visitante</li><li>{{ participante.email }} para o e-mail do visitante</li><li>{{ participante.local_trabalho }} para o cargo / função / local de trabalho do visitante</li><li>{{ data }} para a data de emissão da declaração</li><li>{{ evento.data_inicio }} para a data/hora do início da visita</li><li>{{ evento.data_termino }} para a data/hora do término da visita</li><li>{{ evento.nome }} para o nome do evento</li><li>{{ evento.descricao }} para a descrição do evento</li><li>{% include 'eventos/snippets/comitiva.html' %} para a tabela com toda a comitiva da visita</li></ul>",
                verbose_name="Texto da declaração",
            ),
        ),
        migrations.CreateModel(
            name="Participante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cpf", models.CharField(max_length=30, verbose_name="CPF")),
                (
                    "nome",
                    models.CharField(
                        max_length=100, verbose_name="nome completo"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="e-mail"
                    ),
                ),
                (
                    "local_trabalho",
                    models.TextField(
                        blank=True, verbose_name="local de trabalho / cargo"
                    ),
                ),
                (
                    "casa_legislativa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="casas.orgao",
                        verbose_name="casa legislativa",
                    ),
                ),
                (
                    "evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eventos.evento",
                        verbose_name="evento",
                    ),
                ),
            ],
            options={
                "verbose_name": "participante",
                "verbose_name_plural": "participantes",
                "ordering": ("casa_legislativa", "nome"),
            },
        ),
    ]
