# Generated by Django 5.0.4 on 2024-05-28 13:41

from django.db import migrations
from django.utils import timezone
from sigi.apps.eventos.models import Evento


def carga(apps, schema_editor):
    for evento in Evento.objects.exclude(moodle_courseid=None).filter(
        data_termino__lt=timezone.localtime()
    ):
        try:
            evento.sincroniza_saberes()
            print(f"\t{evento.nome} sincronizado.")
        except Evento.SaberesSyncException as err:
            print(f"\tERRO: {evento.nome}: {err.message}")


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0063_participantesevento_and_more"),
    ]

    operations = [migrations.RunPython(carga, migrations.RunPython.noop)]
