# Generated by Django 5.2.1 on 2025-08-29 13:47

from django.db import migrations

SQL_STMT = """
create view viw_eventos_participante as
select ep.evento_id as id_evento,
       ep.casa_legislativa_id as id_casa,
       ep.cpf,
       ep.nome,
       ep.email,
       ep.local_trabalho
from eventos_participante ep;
grant select on viw_eventos_participante to sigi_qs;
"""
SQL_REVERSE_STMT = "DROP VIEW viw_eventos_participante;"


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0065_participantes_visitas"),
    ]

    operations = [
        migrations.RunSQL(sql=SQL_STMT, reverse_sql=SQL_REVERSE_STMT)
    ]
