# Generated by Django 6.0.5 on 2026-10-08 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("casas", "0027_alter_orgao_email"),
        ("eventos", "0066_viw_eventos_paricipante"),
    ]

    operations = [
        migrations.CreateModel(
            name="LocalVisita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=100, verbose_name="nome do local"
                    ),
                ),
                (
                    "descricao",
                    models.TextField(verbose_name="descrição do local"),
                ),
            ],
            options={
                "verbose_name": "local de visita",
                "verbose_name_plural": "locais de visita",
            },
        ),
        migrations.CreateModel(
            name="Visita",
            fields=[],
            options={
                "verbose_name": "Visita",
                "verbose_name_plural": "Visitas",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("eventos.evento",),
        ),
        migrations.AddField(
            model_name="evento",
            name="pesquisa_previa",
            field=models.URLField(blank=True, verbose_name="pesquisa prévia"),
        ),
        migrations.AlterField(
            model_name="evento",
            name="casa_anfitria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="casas.orgao",
                verbose_name="instituição / casa anfitriã",
            ),
        ),
        migrations.AddField(
            model_name="evento",
            name="local_visita",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="eventos.localvisita",
                verbose_name="local da visita",
            ),
        ),
    ]
