# Generated by Django 6.0.5 on 2026-10-08 15:22

from django.db import migrations


def forward(apps, schema_editor):
    Evento = apps.get_model("eventos", "Evento")
    for visita in Evento.objects.filter(tipo_evento__categoria="V"):
        if visita.convite_set.count() == 1:
            visita.casa_anfitria = visita.convite_set.first().casa
            visita.save()


def backward(apps, schema_editor):
    Evento = apps.get_model("eventos", "Evento")
    Orgao = apps.get_model("casas", "Orgao")
    senado = Orgao.objects.get(tipo__sigla="SF")
    Evento.objects.filter(tipo_evento__categoria="V").update(
        casa_anfitria=senado
    )


class Migration(migrations.Migration):
    dependencies = [
        ("eventos", "0067_localvisita_visita_evento_pesquisa_previa_and_more"),
    ]
    operations = [migrations.RunPython(forward, backward)]
