# Generated by Django 4.0.4 on 2022-06-18 13:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("casas", "0023_funcionario_cpf_funcionario_identidade"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Presidente",
        ),
    ]
