# Generated by Django 4.1.4 on 2022-12-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("casas", "0026_carga_telefone_geral"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orgao",
            name="email",
            field=models.EmailField(
                blank=True, max_length=128, verbose_name="email"
            ),
        ),
    ]
