# Generated by Django 4.0.4 on 2022-05-28 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("casas", "0023_funcionario_cpf_funcionario_identidade"),
        (
            "parlamentares",
            "0004_partido_legenda_alter_cargo_id_alter_coligacao_id_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parlamentar",
            name="pagina_web",
        ),
        migrations.RemoveField(
            model_name="parlamentar",
            name="sexo",
        ),
        migrations.AddField(
            model_name="parlamentar",
            name="casa_legislativa",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="casas.orgao",
                verbose_name="casa legislativa",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="parlamentar",
            name="cpf",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="CPF"
            ),
        ),
        migrations.AddField(
            model_name="parlamentar",
            name="identidade",
            field=models.CharField(
                blank=True,
                help_text="Informe o RG e o órgão emissor.",
                max_length=30,
                verbose_name="Identidade (RG)",
            ),
        ),
        migrations.AddField(
            model_name="parlamentar",
            name="observacoes",
            field=models.TextField(blank=True, verbose_name="observações"),
        ),
        migrations.AddField(
            model_name="parlamentar",
            name="partido",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="parlamentares.partido",
                verbose_name="partido",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="parlamentar",
            name="presidente",
            field=models.BooleanField(default=False, verbose_name="presidente"),
        ),
        migrations.AddField(
            model_name="parlamentar",
            name="redes_sociais",
            field=models.TextField(
                blank=True,
                help_text="Colocar um por linha",
                verbose_name="redes sociais",
            ),
        ),
        migrations.AddField(
            model_name="parlamentar",
            name="telefones",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="telefones"
            ),
        ),
        migrations.AddField(
            model_name="parlamentar",
            name="ult_alteracao",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="última alteração"
            ),
        ),
        migrations.DeleteModel(
            name="Mandato",
        ),
        migrations.DeleteModel(
            name="MembroMesaDiretora",
        ),
        migrations.DeleteModel(
            name="Cargo",
        ),
        migrations.DeleteModel(
            name="SessaoLegislativa",
        ),
        migrations.DeleteModel(
            name="MesaDiretora",
        ),
        migrations.DeleteModel(
            name="ComposicaoColigacao",
        ),
        migrations.DeleteModel(
            name="Coligacao",
        ),
        migrations.DeleteModel(
            name="Legislatura",
        ),
    ]
