# Generated by Django 4.0.4 on 2022-06-18 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0006_alter_partido_sigla'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parlamentar',
            options={'ordering': ('presidente', 'nome_completo'), 'verbose_name_plural': 'parlamentares'},
        ),
    ]
