# Generated by Django 4.0.4 on 2022-06-24 01:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parlamentares", "0008_alter_parlamentar_foto"),
    ]

    operations = [
        migrations.AddField(
            model_name="parlamentar",
            name="ano_eleicao",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Ano de eleição"
            ),
        ),
        migrations.AddField(
            model_name="parlamentar",
            name="flag_importa",
            field=models.CharField(
                blank=True, default="", editable=False, max_length=1
            ),
        ),
        migrations.AddField(
            model_name="parlamentar",
            name="sequencial_tse",
            field=models.CharField(
                blank=True,
                default="",
                editable=False,
                max_length=20,
                verbose_name="Sequencial TSE",
            ),
        ),
        migrations.AddField(
            model_name="parlamentar",
            name="status_mandato",
            field=models.CharField(
                choices=[
                    ("E", "Em exercício"),
                    ("S", "Suplente"),
                    ("I", "Inativo"),
                ],
                default="E",
                max_length=1,
                verbose_name="status do mandato",
            ),
        ),
        migrations.AlterField(
            model_name="parlamentar",
            name="foto",
            field=models.ImageField(
                blank=True,
                height_field="foto_altura",
                max_length=200,
                upload_to="parlamentares/parlamentar/fotos",
                width_field="foto_largura",
            ),
        ),
    ]
