# Generated by Django 4.0.6 on 2022-08-02 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0010_alter_parlamentar_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parlamentar',
            options={'ordering': ('status_mandato', '-presidente', 'nome_completo'), 'verbose_name_plural': 'parlamentares'},
        ),
    ]
