# Generated by Django 4.1 on 2022-08-19 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "contatos",
            "0005_alter_mesorregiao_options_alter_microrregiao_options_and_more",
        ),
        ("parlamentares", "0011_alter_parlamentar_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Senador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.IntegerField(unique=True, verbose_name="código"),
                ),
                (
                    "nome_parlamentar",
                    models.CharField(
                        max_length=100, verbose_name="nome parlamentar"
                    ),
                ),
                (
                    "nome_completo",
                    models.CharField(
                        max_length=100, verbose_name="nome completo"
                    ),
                ),
                (
                    "sexo",
                    models.CharField(
                        choices=[("M", "Masculino"), ("F", "Feminino")],
                        max_length=1,
                        verbose_name="sexo",
                    ),
                ),
                (
                    "forma_tratamento",
                    models.CharField(
                        max_length=50, verbose_name="forma de tratamento"
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="e-mail"),
                ),
                (
                    "partido",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="parlamentares.partido",
                        verbose_name="partido",
                    ),
                ),
                (
                    "uf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contatos.unidadefederativa",
                        verbose_name="UF",
                    ),
                ),
            ],
            options={
                "verbose_name": "senador",
                "verbose_name_plural": "senadores",
                "ordering": ("uf", "nome_parlamentar"),
            },
        ),
    ]
