# Generated by Django 4.2.7 on 2024-02-26 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cronjob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(editable=False, max_length=100, verbose_name='app')),
                ('job_name', models.CharField(editable=False, max_length=100, verbose_name='job')),
                ('expressao_cron', models.CharField(default='* * * * *', help_text="Usar expressoões no formato padrão de CRON: 'minute hour day month day-of-week'. Mais detalhes: <a href='https://help.ubuntu.com/community/CronHowto'>CronHowTo</a>", max_length=100, verbose_name='expressão CRON')),
            ],
            options={
                'verbose_name': 'Cron job',
                'verbose_name_plural': 'Cron jobs',
                'ordering': ('app_name', 'job_name'),
            },
        ),
        migrations.CreateModel(
            name='JobSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iniciar', models.DateTimeField(verbose_name='Iniciar em')),
                ('iniciado', models.DateTimeField(blank=True, null=True, verbose_name='Iniciado em')),
                ('status', models.CharField(choices=[('A', 'Agendado'), ('E', 'Executando'), ('C', 'Concluído')], default='A', max_length=1, verbose_name='estado')),
                ('tempo_gasto', models.DurationField(blank=True, editable=False, null=True, verbose_name='tempo gasto')),
                ('resultado', models.TextField(blank=True, editable=False, verbose_name='resultado da execução')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.cronjob', verbose_name='Cron job')),
            ],
            options={
                'verbose_name': 'Agenda de execução',
                'verbose_name_plural': 'Agenda de execuções',
                'ordering': ('iniciar',),
            },
        ),
    ]
