# Generated by Django 4.2.7 on 2024-03-21 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_cronjob_jobschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parametro', models.CharField(choices=[('ENCERRA_INSCRICAO', 'Encerra inscrições de oficinas no Portal'), ('EMAIL_JOBS', 'E-mail de jobs')], max_length=100, verbose_name='parâmetro')),
                ('valor', models.CharField(max_length=200, verbose_name='valor do parâmettro')),
            ],
            options={
                'verbose_name': 'Parâmetro de configuração',
                'verbose_name_plural': 'Parâmetros de configuração',
                'ordering': ('parametro',),
            },
        ),
    ]
