# Generated by Django 4.2.7 on 2024-03-26 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_config'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobschedule',
            options={'ordering': ('-iniciar',), 'verbose_name': 'Agenda de execução', 'verbose_name_plural': 'Agenda de execuções'},
        ),
        migrations.AddField(
            model_name='cronjob',
            name='manter_logs',
            field=models.PositiveIntegerField(default=30, help_text='Número de dias que os logs de execução serão mantidos na base de dados. Zero significa que o log jamais será apagado.', verbose_name='dias para manter log'),
        ),
    ]
