# Generated by Django 5.0.6 on 2024-07-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0004_alter_jobschedule_options_cronjob_manter_logs"),
    ]

    operations = [
        migrations.AddField(
            model_name="cronjob",
            name="destinatario_email",
            field=models.TextField(
                blank=True,
                help_text="Insira um endereço de e-mail por linha.",
                verbose_name="destinatário(s) de e-mail",
            ),
        ),
        migrations.AddField(
            model_name="cronjob",
            name="digest",
            field=models.CharField(
                choices=[
                    ("N", "Enviar sem digest"),
                    ("D", "Enviar com digest diário"),
                    ("S", "Enviar com digest semanal"),
                ],
                default="N",
                max_length=1,
                verbose_name="digest",
            ),
        ),
        migrations.AddField(
            model_name="jobschedule",
            name="enviado",
            field=models.BooleanField(default=False, verbose_name="enviado"),
        ),
    ]
