# Generated by Django 5.0.6 on 2024-08-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0005_cronjob_destinatario_email_cronjob_digest_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobschedule",
            name="enviado",
        ),
        migrations.AddField(
            model_name="cronjob",
            name="last_digest",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="último envio de digest"
            ),
        ),
    ]
