# Generated by Django 5.2.1 on 2025-11-05 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0006_remove_jobschedule_enviado_cronjob_last_digest"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobschedule",
            name="job",
        ),
        migrations.DeleteModel(
            name="Cronjob",
        ),
        migrations.DeleteModel(
            name="JobSchedule",
        ),
    ]
