# Generated by Django 6.0.4 on 2026-08-06 00:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0007_remove_jobschedule_job_delete_cronjob_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="sigialert",
            name="repeticao",
            field=models.PositiveIntegerField(
                default=3, verbose_name="repetições"
            ),
        ),
        migrations.CreateModel(
            name="AlertViews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "visualizacoes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="visualizações"
                    ),
                ),
                (
                    "alert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="utils.sigialert",
                        verbose_name="alerta",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "visualização",
                "verbose_name_plural": "visualizações",
                "ordering": ("alert", "usuario", "visualizacoes"),
            },
        ),
    ]
