# Generated by Django 6.0.5 on 2026-09-22 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0008_sigialert_repeticao_alertviews"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Config",
        ),
    ]
