# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-23 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0002_auto_20160616_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='email_contato',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de contato'),
        ),
    ]
