# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-23 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0003_auto_20160623_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='osticket',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='C\xf3digo Ticket'),
        ),
    ]
