# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-27 13:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0004_solicitacao_osticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='sistema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicos.TipoServico'),
        ),
        migrations.DeleteModel(
            name='Sistema',
        ),
    ]
