# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 14:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0005_auto_20160627_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacao',
            name='codigo',
        ),
    ]
