# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-16 17:00
from __future__ import absolute_import
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (u'usuarios', u'0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name=u'ConfirmaEmail',
            fields=[
                (u'id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name=u'ID')),
                (u'email', models.EmailField(max_length=254, unique=True, verbose_name=u'Email')),
                (u'confirmado', models.BooleanField(default=False)),
                (u'token', models.CharField(max_length=50, verbose_name=u'Hash do Email')),
                (u'user_id', models.TextField(blank=True, verbose_name=u'ID do Usuário')),
            ],
            options={
                u'verbose_name': u'Email',
                u'verbose_name_plural': u'Emails',
            },
        ),
        migrations.AddField(
            model_name=u'usuario',
            name=u'email_confirmado',
            field=models.BooleanField(default=False, verbose_name=u'Email confirmado?'),
        ),
    ]
