# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-24 08:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import sigi.apps.utils


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_auto_20160623_0829'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CasaLegislativa',
        ),
        migrations.AddField(
            model_name='usuario',
            name='search_text',
            field=sigi.apps.utils.SearchField(default='casa', editable=False, field_names=[b'casa_legislativa']),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='casa_legislativa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casas.CasaLegislativa', verbose_name='Casa Legislativa'),
        ),
    ]
