# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 15:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_auto_20160624_0853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='search_text',
        ),
    ]
