# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_remove_usuario_search_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='habilitado',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='conveniado',
            field=models.BooleanField(default=False, verbose_name='Conveniado?'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='responsavel',
            field=models.BooleanField(default=False, verbose_name='Rspons\xe1vel?'),
        ),
    ]
