# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-29 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_atesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='atesto_conveniado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.Atesto'),
        ),
    ]
