# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-29 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_usuario_atesto_conveniado'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtestoConvenio',
            fields=[
                ('atesto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuarios.Atesto')),
            ],
            bases=('usuarios.atesto',),
        ),
        migrations.CreateModel(
            name='AtestoResponsavel',
            fields=[
                ('atesto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuarios.Atesto')),
            ],
            bases=('usuarios.atesto',),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='atesto_conveniado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.AtestoConvenio'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='responsavel',
            field=models.BooleanField(default=False, verbose_name='Respons\xe1vel?'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='atesto_responsavel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.AtestoResponsavel'),
        ),
    ]
