# Generated by Django 5.0.4 on 2024-05-15 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("convenios", "0035_convenio_data_extincao_convenio_motivo_extincao"),
    ]

    operations = [
        migrations.AddField(
            model_name="convenio",
            name="erro_gescon",
            field=models.BooleanField(
                default=False, max_length=1, verbose_name="erro no Gescon"
            ),
        ),
    ]
