# Generated by Django 6.0.4 on 2026-08-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("convenios", "0038_projeto_termino_indefinido"),
    ]

    operations = [
        migrations.AddField(
            model_name="projeto",
            name="extinto",
            field=models.BooleanField(
                default=False,
                help_text="Indica se este projeto foi extinto e todos os convênios dele devem ser extintos também.",
                verbose_name="extinto",
            ),
        ),
    ]
