# Generated by Django 6.0.4 on 2026-08-31 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("casas", "0027_alter_orgao_email"),
        ("convenios", "0039_projeto_extinto"),
        ("servidores", "0015_limpa_servidores_users"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="convenio",
            options={
                "get_latest_by": "id",
                "ordering": ("id",),
                "verbose_name": "convênio",
                "verbose_name_plural": "convênios",
            },
        ),
        migrations.AddField(
            model_name="convenio",
            name="id_gescon",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="ID do convênio no Gescon"
            ),
        ),
        migrations.AddConstraint(
            model_name="convenio",
            constraint=models.UniqueConstraint(
                condition=models.Q(("id_gescon__isnull", False)),
                fields=("id_gescon",),
                name="unique_id_gescon_if_not_null",
            ),
        ),
    ]
