# Generated by Django 6.0.5 on 2026-09-22 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "convenios",
            "0040_alter_convenio_options_convenio_id_gescon_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="Gescon",
        ),
    ]
